spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/psychology?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=123456

mybatis-plus.mapper-locations=classpath:mapper/*.xml
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.configuration.map-underscore-to-camel-case=true

web.upload.path=d:/XinLi/upload

ai.api-url=https://open.bigmodel.cn/api/paas/v4/chat/completions
ai.api-key=98a5829e654f43f1aff9e8157fc8f503.YHyFokDuT6xpKTwj
ai.model-name=glm-4-flash

server.address=0.0.0.0
server.port=8080
